web:
  build: ./nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
    - php
    - memcache
  volumes_from:
    - php
  environment: { VIRTUAL_HOST: www.oist.dev, PLATFORM_DOCKER: www }
php:
  build: ./php
  restart: always
  ports:
    - "9000:9000"
  volumes:
    - ./www:/var/www/html
  links:
    - database
    - memcache
    - mailhog
  environment: { PLATFORM_DOCKER: www, PHP_IDE_CONFIG: serverName=www.oist.dev }
database:
  command: 'mysqld --user=root --verbose'
  image: 'mariadb'
  ports:
    - "3306:3306"
  volumes:
    - ./data:/var/lib/mysql
    - ./mysql/conf/mysql.cnf:/etc/mysql/my.cnf
    - ./db-seeds:/docker-entrypoint-initdb.d/
  environment: { MYSQL_DATABASE: www, MYSQL_USER: www, MYSQL_PASSWORD: www, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root' }
memcache:
  image: bpressure/alpine-memcached:latest
  ports:
    - "11211:11211"
mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025"
    - "1025:1025"
